### ISSUE TITLE
Update realtime with the newest changes from CycleGAN

### ISSUE THREAD

**Issue by deadmau6** [Vinno97/realtime-pytorch-CycleGAN-and-pix2pix#1]
**Background:**
This is a fork from the original `pytorch-CycleGAN-and-pix2pix`. The original has a bunch of new updates and improved code so it would be nice to update this fork so that the realtime video can use these new features. Luckily I have already patched the realtime feature into the latest release of  `pytorch-CycleGAN-and-pix2pix`, so it should be pretty easy to bring the latest changes of the original into this fork.

**TODO:**
 * Sync this fork with the original
 * Change code so that realtime video feature still works

**Comment by deadmau6** [comment]
I hope that this is a good format, and I would like to take this issue.

**Comment by Vinno97** [comment]
Fixed by #3
