### ISSUE TITLE
Allow video files to run in realtime

### ISSUE THREAD

**Issue by deadmau6** [Vinno97/realtime-pytorch-CycleGAN-and-pix2pix#2]
**Background:**
Currently the command line option for `videosource` accepts type `int` which makes things difficult for using video files. But the `VideoCapture()` class from `opencv`  can accept integers and the file path for a video source.

**TODO:**
The simple solution is to change the command line option and then do the type checking for either a valid file or an integer.

**Comment by Vinno97** [comment]
Fixed by #3
